### ISSUE TITLE
why no implementation for f32 and f64?

### ISSUE THREAD

**Issue by oroulet** [roeeshoshani/binary_serde#1]
technical reason or not done yet?

**Comment by roeeshoshani** [comment]
I forgot about floats, should be pretty simple to add, feel free to create a PR

**Comment by oroulet** [comment]
I have to admit I have a hard time reading that code, but maybe it is a good challenge...

**Comment by oroulet** [comment]
looking at the code now. As far as I can see, that macro is called xx_int_type but code would be exactly the same for floats...
So basically , we just need to add f32 and f34 to https://github.com/roeeshoshani/binary_serde/blob/main/src/lib.rs#L202C1-L202C39 and rename macro so it makes sense to use it for floats

**Comment by oroulet** [comment]
https://github.com/roeeshoshani/binary_serde/pull/2

**Comment by roeeshoshani** [comment]
Yes, sounds about right.
